#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const INPUT_PATH = path.join(ROOT, "affiliate.offers.seed.json");
const OUTPUT_JSON = path.join(ROOT, "affiliate.offers.ranked.json");
const OUTPUT_MD = path.join(ROOT, "AFFILIATE_OFFERS_RANKED.md");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function round2(value) {
  return Math.round(value * 100) / 100;
}

function weightedScore(scores, weights) {
  return round2(
    scores.demand * weights.demand +
      scores.margin * weights.margin +
      scores.contentEase * weights.contentEase +
      scores.policySafety * weights.policySafety +
      scores.seasonality * weights.seasonality
  );
}

function rankOffers(rawOffers, weights) {
  return rawOffers
    .map((offer) => ({
      ...offer,
      weightedScore: weightedScore(offer.scores, weights),
    }))
    .sort((a, b) => b.weightedScore - a.weightedScore);
}

function renderMarkdown(digital, amazon) {
  const header = [
    "# Ranked Affiliate Offers",
    "",
    "Generated by `npm run affiliate:score`.",
    "",
    "## Digital Offers (ClickBank + Hotmart)",
    "",
    "| Rank | Offer | Network | Niche | Score |",
    "|---|---|---|---|---|",
  ];

  const digitalRows = digital.map(
    (offer, index) =>
      `| ${index + 1} | ${offer.name} | ${offer.network} | ${offer.niche} | ${offer.weightedScore} |`
  );

  const amazonHeader = [
    "",
    "## Amazon Products",
    "",
    "| Rank | Product | Category | Niche | Score |",
    "|---|---|---|---|---|",
  ];

  const amazonRows = amazon.map(
    (offer, index) =>
      `| ${index + 1} | ${offer.name} | ${offer.category} | ${offer.niche} | ${offer.weightedScore} |`
  );

  return [...header, ...digitalRows, ...amazonHeader, ...amazonRows, ""].join("\n");
}

function main() {
  if (!fs.existsSync(INPUT_PATH)) {
    throw new Error(`Missing input file: ${INPUT_PATH}`);
  }

  const config = readJson(INPUT_PATH);
  const weights = config.weights;
  const rankedDigital = rankOffers(config.digital_offers, weights);
  const rankedAmazon = rankOffers(config.amazon_products, weights);

  const payload = {
    generatedAt: new Date().toISOString(),
    weights,
    digital_offers: rankedDigital,
    amazon_products: rankedAmazon,
  };

  fs.writeFileSync(OUTPUT_JSON, JSON.stringify(payload, null, 2), "utf8");
  fs.writeFileSync(OUTPUT_MD, renderMarkdown(rankedDigital, rankedAmazon), "utf8");

  console.log("Offer ranking generated:");
  console.log(`- ${OUTPUT_JSON}`);
  console.log(`- ${OUTPUT_MD}`);
}

main();
